import Link from "next/link";

const REPO_BASE =
  "https://github.com/dodopayments/dualmark/edit/main/apps/docs/content/docs/";

interface DocsPageFooterProps {
  filePath: string | undefined;
  isAutoGenerated?: boolean;
}

export function DocsPageFooter({
  filePath,
  isAutoGenerated,
}: DocsPageFooterProps) {
  if (!filePath) return null;

  const editHref = isAutoGenerated
    ? "https://github.com/dodopayments/dualmark/tree/main/spec"
    : `${REPO_BASE}${filePath}`;

  const editLabel = isAutoGenerated
    ? "Edit on GitHub (spec source)"
    : "Edit this page on GitHub";

  return (
    <div className="mt-12 flex flex-col gap-3 border-t border-[var(--color-border)] pt-6 text-sm text-[var(--color-fg-muted)] sm:flex-row sm:items-center sm:justify-between">
      <Link
        href={editHref}
        target="_blank"
        rel="noreferrer"
        className="inline-flex items-center gap-2 text-[var(--color-fg-muted)] transition-colors hover:text-[var(--color-accent)]"
      >
        <PencilIcon className="size-3.5" />
        {editLabel}
        <ArrowIcon className="size-3" />
      </Link>
      <span className="font-mono text-[11px] uppercase tracking-wider text-[var(--color-fg-subtle)]">
        {isAutoGenerated ? "Auto-generated from /spec/" : "Last updated by repo"}
      </span>
    </div>
  );
}

function PencilIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" className={className} aria-hidden>
      <path
        d="m15.5 4.5 4 4L8 20H4v-4L15.5 4.5Z"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinejoin="round"
      />
    </svg>
  );
}
function ArrowIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" className={className} aria-hidden>
      <path
        d="M7 17 17 7m0 0H8m9 0v9"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
      />
    </svg>
  );
}
